### ISSUE TITLE
ERROR "Module did not self-register" in woker threads

### ISSUE THREAD

**Issue by gorphone** [Julusian/node-jpeg-turbo#7]
Require @julusian/jpeg-turbo in the worker thread file, throwing error:
Module did not self-register: '/Users/***/work/stf-provider/node_modules/@julusian/jpeg-turbo/build/Release/jpegturbo.node'.
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at bindings (/Users/gaofeng/work/stf-provider/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/Users/gaofeng/work/stf-provider/node_modules/@julusian/jpeg-turbo/index.js:1:34)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/gaofeng/work/stf-provider/lib/units/device/plugins/vnc/index.js:8:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

**Comment by Julusian** [comment]
I'm going to need some more information to be able to help here.

What version of node are you using?
What version of the library are you using? prebuilt binary or built from source?
Does this only happen for you when in a worker_thread, and not in the main thread?

**Comment by gorphone** [comment]
node 12.22.9
library: 0.5.4, 0.5.6, 1.1.1 prebuilt binary

just in a woker_thread, has not test the main thread

**Comment by gorphone** [comment]
It's wired that 1.1.1 work fine in Linux and bad in Mac OS,  WHILE 0.5.x work fine in  Mac OS and bad in Linux
